### ISSUE TITLE
Authorization header seems backward compared to OpenHaystack

### ISSUE THREAD

**Issue by biemster** [lennyerik/windows-anisette#1]
In the README the authorization header reads `BASE64("search-party-token:appleid_uuid")`, while the code in OpenHaystack is
```
NSString *authText = [NSString stringWithFormat:@"%@:%@", appleId, tokenString];
NSString *base64Auth = [[authText dataUsingEncoding:NSUTF8StringEncoding] base64EncodedStringWithOptions:0];
```
This seems to be the wrong way around (although I'm not 100% sure since I did not succeed in crafting a working query). I'm trying to replicate the retrieval of the reports in a shell script (https://github.com/biemster/FindMy/blob/main/request_reports.sh), but did not succeed yet.

**Comment by lennyerik** [comment]
Yes, I'm pretty sure the parameters are the wrong way round in the README / actual code. Since this is technically a proof-of-concept for generating the anisette-data, which is not actually capable of generating the search-party-token I was probably just lazy and didn't pay attention when looking at OpenHaystack's code... :smile: 
Anyway, issue is now fixed.
